"""Decide which plugins a pull request changed without bumping their version.

The installer keys on the ``version`` field in
``plugins/<name>/.claude-plugin/plugin.json``, and a session loads from
``~/.claude/plugins/cache/plugin-place/<name>/<version>/``. A change merged
without a version bump therefore reaches no installed copy: ``/reload-plugins``
reports success and loads the old code. PR #77 fixed the laconic slash-command
tracker and reached nobody, because the version stayed ``0.2.0``.

Two modes over one decision:

``plan``/``apply``
    Same-repo pull requests. The workflow bumps the patch component on the PR's
    own branch, so the bump lands in the same PR as the fix and nothing ever
    pushes to ``main``.
``check``
    Fork pull requests, where the token cannot push to the contributor's
    branch. Reports the same plugins and fails, naming the file to edit.

Only ``kind: local`` plugins are eligible. Every other kind under ``plugins/``
is generated by ``scripts/render.py``: ``built`` and ``agents`` hardcode
``0.1.0``, ``vendored`` reads the upstream marketplace metadata, and
``vendored-whole`` derives from the pinned tag. Writing a version into one of
those would be erased by the next ``scripts/build.sh`` and would fail the CI
step that asserts the committed tree matches a fresh build. That is also why
this never fights ``sync-upstream.yml``: sync PRs touch generated plugins only.
"""

import json
import re
import subprocess
from dataclasses import dataclass
from pathlib import Path

PLUGINS_DIR = "plugins"
MANIFEST_RELPATH = ".claude-plugin/plugin.json"
LOCAL_KIND = "local"

_SEMVER_RE = re.compile(r"^(\d+)\.(\d+)\.(\d+)$")


class VersionError(Exception):
    """A plugin manifest cannot be read or bumped. Always names the file."""


@dataclass(frozen=True)
class Bump:
    """One plugin that changed with no version change of its own."""

    plugin: str
    manifest: str
    old: str
    new: str

    def describe(self):
        return f"{self.plugin}: {self.old} -> {self.new} ({self.manifest})"


@dataclass(frozen=True)
class Skip:
    """A touched plugin this tool deliberately left alone, and why."""

    plugin: str
    reason: str


def manifest_path(plugin):
    return f"{PLUGINS_DIR}/{plugin}/{MANIFEST_RELPATH}"


def plugins_touched(paths):
    """Plugin names owning any of ``paths``, sorted, deduplicated.

    No file class is exempt. Everything under ``plugins/<name>/`` is copied into
    the installed plugin directory, a README included, so a docs-only change
    ships too and a reader of the installed copy would otherwise see the old
    text under a version that claims to be current.
    """
    found = set()
    for path in paths:
        parts = Path(path).as_posix().split("/")
        if len(parts) >= 3 and parts[0] == PLUGINS_DIR and parts[1]:
            found.add(parts[1])
    return sorted(found)


def local_plugin_names(config):
    """Names of ``kind: local`` plugins in a parsed plugins.yaml."""
    names = set()
    for entry in config.get("plugins") or []:
        if not isinstance(entry, dict) or entry.get("kind") != LOCAL_KIND:
            continue
        name = entry.get("name")
        if not name:
            raise VersionError("plugins.yaml: a `kind: local` entry has no `name`")
        names.add(name)
    return names


def read_version(text, where):
    """The ``version`` string from manifest ``text``, loudly.

    A local plugin with no version is unpublishable in practice: the installer
    has nothing to key a cache directory on. Say so rather than inventing one.
    """
    try:
        data = json.loads(text)
    except json.JSONDecodeError as e:
        raise VersionError(f"{where}: not valid JSON ({e})") from e
    version = data.get("version")
    if version is None:
        raise VersionError(
            f"{where}: no \"version\" field. Add one (semver, e.g. \"0.1.0\") — "
            "the installer keys its cache directory on it."
        )
    if not isinstance(version, str):
        raise VersionError(f"{where}: \"version\" must be a string, got {type(version).__name__}")
    return version


def bump_patch(version, where):
    """``X.Y.Z`` with Z incremented. Anything else fails, naming the file."""
    m = _SEMVER_RE.match(version)
    if not m:
        raise VersionError(
            f"{where}: version {version!r} is not X.Y.Z, so this tool will not "
            "guess the next one. Set a semver version by hand."
        )
    major, minor, patch = (int(g) for g in m.groups())
    return f"{major}.{minor}.{patch + 1}"


def plan(changed_paths, local_names, version_at_base, version_at_head):
    """Bumps needed, plus the touched plugins skipped and why.

    ``version_at_base`` and ``version_at_head`` take a plugin name and return
    its version string, or ``None`` when the manifest does not exist at that
    point. They may raise :class:`VersionError` for a manifest that exists but
    cannot be read; that propagates, because a local plugin with an unreadable
    version is exactly the case this gate must not wave through.
    """
    bumps, skips = [], []
    for name in plugins_touched(changed_paths):
        if name not in local_names:
            skips.append(Skip(name, "generated by scripts/render.py, version is not hand-held"))
            continue
        head = version_at_head(name)
        if head is None:
            skips.append(Skip(name, "no manifest at the head commit; plugin removed or renamed"))
            continue
        base = version_at_base(name)
        if base is None:
            skips.append(Skip(name, "new plugin in this PR; no installed copy can be stale"))
            continue
        if head != base:
            # Any change counts, in either direction. The author's judgement of
            # patch versus minor is theirs, and a deliberate revert is still a
            # decision this tool has no standing to overrule.
            skips.append(Skip(name, f"already bumped by the author ({base} -> {head})"))
            continue
        bumps.append(Bump(name, manifest_path(name), head, bump_patch(head, manifest_path(name))))
    return bumps, skips


def rewrite_version(text, old, new, where):
    """``text`` with the one ``"version": "<old>"`` occurrence set to ``new``.

    A targeted substitution rather than a JSON round-trip: these manifests are
    hand-formatted and a reserialise would rewrite unrelated bytes, burying a
    one-field bump in a whole-file diff.
    """
    pattern = re.compile(r'("version"\s*:\s*")' + re.escape(old) + r'(")')
    text, count = pattern.subn(lambda m: m.group(1) + new + m.group(2), text)
    if count != 1:
        raise VersionError(
            f"{where}: expected exactly one \"version\": \"{old}\" to rewrite, found {count}"
        )
    return text


def apply_bumps(bumps, repo_root):
    """Write each bump to disk. Returns the manifest paths written."""
    written = []
    for bump in bumps:
        path = Path(repo_root) / bump.manifest
        text = path.read_text()
        path.write_text(rewrite_version(text, bump.old, bump.new, bump.manifest))
        written.append(bump.manifest)
    return written


# ── git layer ────────────────────────────────────────────────────────────────


def git(repo_root, *args):
    proc = subprocess.run(
        ["git", "-C", str(repo_root), *args], capture_output=True, text=True
    )
    if proc.returncode != 0:
        raise VersionError(
            f"git {' '.join(args)} failed ({proc.returncode}): {proc.stderr.strip()}"
        )
    return proc.stdout


def merge_base(repo_root, base_ref, head="HEAD"):
    return git(repo_root, "merge-base", base_ref, head).strip()


def changed_since(repo_root, base_sha, head="HEAD"):
    # --no-renames: rename detection reports only the destination, so a file
    # moved out of one plugin into another would leave the losing plugin
    # unflagged while its installed copy still ships the file.
    out = git(repo_root, "diff", "--name-only", "--no-renames", base_sha, head)
    return [line for line in out.splitlines() if line]


def version_reader_at(repo_root, ref):
    """A ``version_at_base``-shaped callable reading a manifest at ``ref``."""

    def read(name):
        path = manifest_path(name)
        # ls-tree first: it exits 0 with empty output when the path is simply
        # absent, and fails for a bad ref or a broken object. Reading a `git
        # show` failure as absence would turn any git error into a silent skip,
        # which is the exact under-bumping this tool exists to stop.
        if not git(repo_root, "ls-tree", "-z", ref, "--", path).strip("\0"):
            return None
        return read_version(
            git(repo_root, "show", f"{ref}:{path}"), f"{path} at {ref}"
        )

    return read


def version_reader_worktree(repo_root):
    """A ``version_at_head``-shaped callable reading the checked-out tree.

    The worktree, not the head commit: ``--apply`` edits the worktree, so a
    second run in the same checkout must see the bump it just made.
    """

    def read(name):
        path = Path(repo_root) / manifest_path(name)
        if not path.is_file():
            return None
        return read_version(path.read_text(), manifest_path(name))

    return read


# ── entry point ──────────────────────────────────────────────────────────────

GATE_ADVICE = (
    "Edit the \"version\" in each file above: patch (0.0.X) for a fix, "
    "minor (0.X.0) for new behaviour. Without it the change merges and reaches "
    "no installed copy, because the installer caches per version."
)


def load_local_names(repo_root):
    import yaml  # imported here so the pure logic above needs no PyYAML

    path = Path(repo_root) / "plugins.yaml"
    try:
        config = yaml.safe_load(path.read_text())
    except (OSError, yaml.YAMLError) as e:
        raise VersionError(f"{path}: could not read ({type(e).__name__}: {e})") from e
    return local_plugin_names(config or {})


def main(argv=None):
    import argparse
    import sys

    parser = argparse.ArgumentParser(
        description="Bump the patch version of any local plugin this PR changed without one."
    )
    parser.add_argument("--repo", default=".", help="repository root (default: cwd)")
    parser.add_argument(
        "--base-ref",
        default="origin/main",
        help="branch the PR targets; the comparison point is its merge base with HEAD",
    )
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument(
        "--apply", action="store_true", help="write the bumps (same-repo pull requests)"
    )
    mode.add_argument(
        "--check",
        action="store_true",
        help="exit 1 naming what needs a bump, writing nothing (fork pull requests)",
    )
    args = parser.parse_args(argv)

    repo_root = Path(args.repo).resolve()
    try:
        base_sha = merge_base(repo_root, args.base_ref)
        changed = changed_since(repo_root, base_sha)
        bumps, skips = plan(
            changed,
            load_local_names(repo_root),
            version_reader_at(repo_root, base_sha),
            version_reader_worktree(repo_root),
        )
    except VersionError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2

    for skip in skips:
        print(f"note: {skip.plugin} left alone: {skip.reason}", file=sys.stderr)

    if not bumps:
        print(f"no plugin needs a version bump (base {base_sha[:12]})")
        return 0

    if args.check:
        print("These plugins changed with no version change of their own:")
        for bump in bumps:
            print(f"  {bump.plugin}: still {bump.old} ({bump.manifest})")
        print(GATE_ADVICE)
        return 1

    if not args.apply:
        for bump in bumps:
            print(f"would bump {bump.describe()}")
        return 0

    try:
        apply_bumps(bumps, repo_root)
    except VersionError as e:
        print(f"error: {e}", file=sys.stderr)
        return 2
    for bump in bumps:
        print(f"bumped {bump.describe()}")
    return 0
