#!/usr/bin/env python3
"""
render.py — invoked by build.sh. Reads plugins.yaml and produces:
  - plugins/<name>/{.claude-plugin/plugin.json, skills/, commands/, README.md}
  - .claude-plugin/marketplace.json
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_YAML = REPO_ROOT / "plugins.yaml"
PLUGINS_DIR = REPO_ROOT / "plugins"
PATCHES_DIR = REPO_ROOT / "patches"
MARKETPLACE_JSON = REPO_ROOT / ".claude-plugin" / "marketplace.json"


def submodule_sha(path: Path) -> str:
    """Get the commit SHA of a submodule for reproducibility metadata."""
    return subprocess.check_output(
        ["git", "-C", str(path), "rev-parse", "HEAD"], text=True
    ).strip()


def submodule_describe(path: Path) -> str:
    """Get the tag/description of a submodule, fall back to SHA prefix."""
    try:
        return subprocess.check_output(
            ["git", "-C", str(path), "describe", "--tags", "--exact-match"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        return submodule_sha(path)[:12]


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def clean_built_plugins() -> None:
    """Remove plugins/ entries that are regenerated (built + vendored).
    Local plugins (kind: local) are NEVER touched."""
    if not PLUGINS_DIR.exists():
        return
    config = yaml.safe_load(PLUGINS_YAML.read_text())
    regenerated = {
        p["name"]
        for p in config["plugins"]
        if p["kind"] in ("built", "vendored", "vendored-whole")
    }
    for entry in PLUGINS_DIR.iterdir():
        if entry.is_dir() and entry.name in regenerated:
            shutil.rmtree(entry)


def build_built_plugin(plugin: dict, upstream: dict) -> None:
    """Copy skills from upstream submodule into plugins/<name>/skills/."""
    name = plugin["name"]
    submodule_path = REPO_ROOT / upstream["submodule"]
    skills_root = submodule_path / upstream["skills_root"]

    plugin_dir = PLUGINS_DIR / name
    skills_dir = plugin_dir / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    missing = []
    for skill_name in plugin["skills"]:
        src = skills_root / skill_name
        if not src.is_dir():
            missing.append(skill_name)
            continue
        if not (src / "SKILL.md").exists():
            print(f"WARN: {name}/{skill_name} has no SKILL.md", file=sys.stderr)
        shutil.copytree(src, skills_dir / skill_name)

    if missing:
        raise SystemExit(
            f"ERROR: plugin {name!r} references skills not present in "
            f"{upstream['submodule']} @ {upstream['pinned_tag']}: {missing}"
        )

    write_json(
        plugin_dir / ".claude-plugin" / "plugin.json",
        {
            "name": name,
            "version": "0.1.0",
            "description": plugin["description"],
            "author": {"name": "galeep"},
            "homepage": "https://github.com/galeep/plugin-place",
            "license": upstream["license"],
            "keywords": ["scientific-skills", upstream["upstream_repo"].split("/")[1]],
        },
    )

    readme = plugin_dir / "README.md"
    skill_list = "\n".join(f"- `{s}`" for s in plugin["skills"])
    readme.write_text(
        f"""# {name}

{plugin["description"]}

## Skills ({len(plugin["skills"])})

{skill_list}

## Provenance

Built from [{upstream['upstream_repo']}](https://github.com/{upstream['upstream_repo']}) @ `{upstream['pinned_tag']}`.
Skills are vendored copies under [MIT license]({upstream['license']}). All credit to K-Dense AI.

This plugin is generated by `scripts/build.sh` from `plugins.yaml`. Edits here will be overwritten on rebuild.
"""
    )


def build_vendored_plugin(plugin: dict, upstream: dict) -> None:
    """Copy a complete upstream plugin into plugins/<name>/, generate plugin.json."""
    name = plugin["name"]
    submodule_path = REPO_ROOT / upstream["submodule"]
    plugin_dir = PLUGINS_DIR / name
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Copy skills and commands wholesale if they exist upstream.
    for subdir in ("skills", "commands", "agents", "hooks"):
        src = submodule_path / subdir
        if src.is_dir():
            shutil.copytree(src, plugin_dir / subdir)

    # Drop container directories under skills/ that are not themselves skills
    # (no SKILL.md at their root). K-Dense's writer ships `document-skills/`
    # as a container with 4 sub-skills inside, but Claude Code expects skills
    # one level deep under skills/. Those skills are split into their own
    # `built` plugin (see kdense-document-skills); we drop the container here
    # to keep the writer plugin valid.
    skills_root_dir = plugin_dir / "skills"
    if skills_root_dir.is_dir():
        for container in list(skills_root_dir.iterdir()):
            if not container.is_dir() or (container / "SKILL.md").exists():
                continue
            print(f"  dropping container directory: {container.name}/", file=sys.stderr)
            shutil.rmtree(container)

    # If upstream has .mcp.json or .lsp.json at root, copy those too.
    for mcp_file in (".mcp.json", ".lsp.json"):
        src = submodule_path / mcp_file
        if src.is_file():
            shutil.copy2(src, plugin_dir / mcp_file)

    # Generate plugin.json — pull metadata from upstream marketplace.json if present.
    upstream_marketplace = submodule_path / ".claude-plugin" / "marketplace.json"
    description = plugin["description"]
    version = "0.1.0"
    if upstream_marketplace.exists():
        try:
            data = json.loads(upstream_marketplace.read_text())
            version = data.get("metadata", {}).get("version", version)
        except Exception:
            pass

    write_json(
        plugin_dir / ".claude-plugin" / "plugin.json",
        {
            "name": name,
            "version": version,
            "description": description,
            "author": {"name": "K-Dense Inc.", "email": "contact@k-dense.ai"},
            "homepage": f"https://github.com/{upstream['upstream_repo']}",
            "license": upstream["license"],
        },
    )

    plugin_dir.joinpath("README.md").write_text(
        f"""# {name}

{description}

## Provenance

Vendored from [{upstream['upstream_repo']}](https://github.com/{upstream['upstream_repo']}) @ `{upstream['pinned_tag']}`.
Licensed under {upstream['license']}. All credit to K-Dense AI.

This plugin is generated by `scripts/build.sh` from `plugins.yaml`. Edits here will be overwritten on rebuild.
"""
    )


def build_vendored_whole_plugin(plugin: dict, upstream: dict) -> None:
    """Copy a complete upstream plugin whose layout does NOT match the simple
    skills-at-root shape build_vendored_plugin assumes.

    Unlike build_vendored_plugin, this PRESERVES the upstream
    .claude-plugin/plugin.json verbatim (it can wire hooks, MCP servers, etc.
    that a generated manifest would silently drop) and copies the plugin's own
    source tree (e.g. src/ that the hooks call). Used for caveman, whose repo
    root is the plugin and whose hooks live in src/hooks/ referenced from
    plugin.json.

    Only a curated set of TOP-LEVEL entries is copied. Platform-variant dirs
    (.codex, .junie, ...), dev tooling (tests, evals, benchmarks), and package
    metadata are intentionally excluded. Note `src/` is copied whole, so inert
    subtrees inside it (e.g. src/plugins/opencode, src/mcp-servers) ride along;
    they are not wired by the preserved plugin.json and are harmless, but the
    curation is top-level only, not recursive into src/.
    """
    name = plugin["name"]
    submodule_path = REPO_ROOT / upstream["submodule"]
    # Allow the plugin to live in a subdir of the submodule; default is root.
    src_root = submodule_path / upstream.get("plugin_root", ".")
    plugin_dir = PLUGINS_DIR / name
    plugin_dir.mkdir(parents=True, exist_ok=True)

    copy_dirs = ("skills", "commands", "agents", "hooks", "src", "assets")
    copy_files = ("LICENSE",)
    for d in copy_dirs:
        s = src_root / d
        if s.is_dir():
            shutil.copytree(s, plugin_dir / d)
    for f in copy_files:
        s = src_root / f
        if s.is_file():
            shutil.copy2(s, plugin_dir / f)

    # Preserve the upstream manifest verbatim (NOT regenerated) so its hooks/MCP
    # wiring survives. Copy only plugin.json out of .claude-plugin/ — the
    # upstream marketplace.json must not leak into the plugin dir.
    upstream_manifest = src_root / ".claude-plugin" / "plugin.json"
    if not upstream_manifest.is_file():
        raise SystemExit(
            f"vendored-whole plugin {name!r}: no .claude-plugin/plugin.json at "
            f"{src_root} — cannot preserve manifest"
        )
    manifest = json.loads(upstream_manifest.read_text())
    # Backfill a semver version if upstream omits one (validate-plugin.sh warns
    # otherwise). Derive from the pinned tag (vX.Y.Z -> X.Y.Z).
    manifest.setdefault("version", upstream["pinned_tag"].lstrip("v"))
    write_json(plugin_dir / ".claude-plugin" / "plugin.json", manifest)

    plugin_dir.joinpath("README.md").write_text(
        f"""# {name}

{plugin["description"]}

## Provenance

Vendored whole from [{upstream['upstream_repo']}](https://github.com/{upstream['upstream_repo']}) @ `{upstream['pinned_tag']}`.
Licensed under {upstream['license']}. All credit to the upstream author.

Downstream edits (if any) are applied from `patches/{name}.json` on every build
and fail the build if an anchor no longer matches upstream. This directory is
generated by `scripts/build.sh`; edit `patches/{name}.json`, not these files.
"""
    )


def apply_downstream_patches(plugin_name: str, required: bool = False) -> int:
    """Apply patches/<plugin_name>.json to the freshly built plugin tree.

    Each edit is an exact-substring find/replace (the same idiom the upstream
    sync workflow uses to bump plugins.yaml). The anchor MUST occur exactly
    once or the build aborts: a missing anchor means upstream changed the
    patched region (drift we must review and re-derive), and a duplicate anchor
    means the edit is ambiguous. Either way a guessed change is never applied
    silently.

    Fail-loud is the whole point, so every way the patch layer could quietly
    do nothing is also an abort: a declared-but-missing patch file (`required`),
    malformed JSON, a missing/typo'd "edits" key, a missing per-edit key, and a
    patch file that yields zero applied edits.

    HARD INVARIANT: this runs on a PRISTINE tree (clean_built_plugins wiped it,
    the build recopied upstream, then we patch). It is NOT re-entrant — an
    anchor that is a substring of its own replacement would duplicate content on
    a second pass, so we abort if the replacement text is already present.

    Returns the number of edits applied (0 only when no patch file exists and
    the plugin did not declare one).
    """
    patch_file = PATCHES_DIR / f"{plugin_name}.json"
    if not patch_file.exists():
        if required:
            raise SystemExit(
                f"patch {plugin_name}: plugins.yaml sets `patched: true` but "
                f"{patch_file} is missing — refusing to publish an unpatched plugin"
            )
        return 0

    try:
        spec = json.loads(patch_file.read_text())
    except json.JSONDecodeError as e:
        raise SystemExit(f"patch {plugin_name}: malformed JSON in {patch_file}: {e}")

    if not isinstance(spec.get("edits"), list):
        raise SystemExit(
            f'patch {plugin_name}: {patch_file} has no "edits" list '
            f"(a typo'd key would otherwise silently apply nothing)"
        )

    plugin_dir = PLUGINS_DIR / plugin_name
    applied = 0
    for i, edit in enumerate(spec["edits"]):
        for key in ("file", "find", "replace"):
            if key not in edit:
                raise SystemExit(
                    f"patch {plugin_name} edit #{i}: missing required key {key!r}"
                )
        rel = edit["file"]
        target = plugin_dir / rel
        if not target.is_file():
            raise SystemExit(
                f"patch {plugin_name} edit #{i}: target file not found: {rel}"
            )

        content = target.read_text()
        if edit["replace"] in content:
            raise SystemExit(
                f"patch {plugin_name} edit #{i}: replacement already present in "
                f"{rel} — non-pristine tree (patches must run on a fresh build)"
            )
        find = edit["find"]
        occurrences = content.count(find)
        if occurrences == 0:
            raise SystemExit(
                f"patch {plugin_name} edit #{i}: DRIFT — anchor not found in {rel} "
                f"(upstream likely changed it). Re-derive the patch. "
                f"Anchor starts: {find[:70]!r}"
            )
        if occurrences > 1 and not edit.get("all", False):
            raise SystemExit(
                f"patch {plugin_name} edit #{i}: AMBIGUOUS — anchor occurs "
                f'{occurrences}x in {rel}; make it unique or set "all": true. '
                f"Anchor starts: {find[:70]!r}"
            )
        target.write_text(content.replace(find, edit["replace"]))
        applied += 1

    if applied == 0:
        raise SystemExit(
            f"patch {plugin_name}: {patch_file} present but applied 0 edits "
            f"— refusing a silent no-op patch layer"
        )
    return applied


def build_marketplace(config: dict) -> None:
    entries = []
    for plugin in config["plugins"]:
        entry = {
            "name": plugin["name"],
            "description": plugin["description"],
            "source": f"./plugins/{plugin['name']}",
        }
        if "category" in plugin:
            entry["category"] = plugin["category"]
        entries.append(entry)

    market = config["marketplace"]
    output = {
        "$schema": "https://json.schemastore.org/claude-code-marketplace.json",
        "name": market["name"],
        "version": market.get("version", "0.1.0"),
        "description": market["description"],
        "owner": market["owner"],
        "plugins": entries,
    }
    if "homepage" in market:
        output["metadata"] = {"homepage": market["homepage"]}
    write_json(MARKETPLACE_JSON, output)


def write_provenance_sidecar(config: dict) -> None:
    """Write a small JSON file recording exactly which upstream commits we built from.
    CI compares this to detect drift."""
    upstreams = {}
    for name, up in config["upstreams"].items():
        submodule_path = REPO_ROOT / up["submodule"]
        upstreams[name] = {
            "pinned_tag": up["pinned_tag"],
            "sha": submodule_sha(submodule_path),
            "describe": submodule_describe(submodule_path),
            "repo": up["upstream_repo"],
        }
    write_json(REPO_ROOT / ".claude-plugin" / "provenance.json", upstreams)


def main():
    config = yaml.safe_load(PLUGINS_YAML.read_text())

    clean_built_plugins()

    built = vendored = vendored_whole = 0
    for plugin in config["plugins"]:
        kind = plugin["kind"]
        upstream_name = plugin.get("upstream")
        if kind in ("built", "vendored", "vendored-whole"):
            if upstream_name not in config["upstreams"]:
                raise SystemExit(
                    f"plugin {plugin['name']} references unknown upstream {upstream_name!r}"
                )
            upstream = config["upstreams"][upstream_name]

        if kind == "built":
            build_built_plugin(plugin, upstream)
            built += 1
        elif kind == "vendored":
            build_vendored_plugin(plugin, upstream)
            vendored += 1
        elif kind == "vendored-whole":
            build_vendored_whole_plugin(plugin, upstream)
            vendored_whole += 1
        elif kind == "local":
            # local plugins live untouched in plugins/<name>/ already
            pass
        else:
            raise SystemExit(f"unknown plugin kind: {kind!r}")

    # Apply downstream patches AFTER every plugin tree is in place. The tree was
    # just recopied pristine from upstream (clean_built_plugins wiped it first),
    # so re-applying here is idempotent. A missing or non-unique anchor aborts
    # the build: upstream drift is surfaced, never silently absorbed.
    patched_files = 0
    for plugin in config["plugins"]:
        patched_files += apply_downstream_patches(
            plugin["name"], required=plugin.get("patched", False)
        )

    build_marketplace(config)
    write_provenance_sidecar(config)

    print(
        f"render.py: built={built} vendored={vendored} "
        f"vendored-whole={vendored_whole} patched-edits={patched_files} "
        f"total={len(config['plugins'])}"
    )


if __name__ == "__main__":
    main()
