#!/usr/bin/env python3
"""
render.py — invoked by build.sh. Reads plugins.yaml and produces:
  - plugins/<name>/{.claude-plugin/plugin.json, skills/, commands/, README.md}
  - .claude-plugin/marketplace.json
"""
import json
import shutil
import subprocess
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    print("PyYAML required. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

REPO_ROOT = Path(__file__).resolve().parent.parent
PLUGINS_YAML = REPO_ROOT / "plugins.yaml"
PLUGINS_DIR = REPO_ROOT / "plugins"
MARKETPLACE_JSON = REPO_ROOT / ".claude-plugin" / "marketplace.json"


def submodule_sha(path: Path) -> str:
    """Get the commit SHA of a submodule for reproducibility metadata."""
    return subprocess.check_output(
        ["git", "-C", str(path), "rev-parse", "HEAD"], text=True
    ).strip()


def submodule_describe(path: Path) -> str:
    """Get the tag/description of a submodule, fall back to SHA prefix."""
    try:
        return subprocess.check_output(
            ["git", "-C", str(path), "describe", "--tags", "--exact-match"],
            text=True,
            stderr=subprocess.DEVNULL,
        ).strip()
    except subprocess.CalledProcessError:
        return submodule_sha(path)[:12]


def write_json(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(data, indent=2) + "\n")


def clean_built_plugins() -> None:
    """Remove plugins/ entries that are regenerated (built + vendored).
    Local plugins (kind: local) are NEVER touched."""
    if not PLUGINS_DIR.exists():
        return
    config = yaml.safe_load(PLUGINS_YAML.read_text())
    regenerated = {
        p["name"] for p in config["plugins"] if p["kind"] in ("built", "vendored")
    }
    for entry in PLUGINS_DIR.iterdir():
        if entry.is_dir() and entry.name in regenerated:
            shutil.rmtree(entry)


def build_built_plugin(plugin: dict, upstream: dict) -> None:
    """Copy skills from upstream submodule into plugins/<name>/skills/."""
    name = plugin["name"]
    submodule_path = REPO_ROOT / upstream["submodule"]
    skills_root = submodule_path / upstream["skills_root"]

    plugin_dir = PLUGINS_DIR / name
    skills_dir = plugin_dir / "skills"
    skills_dir.mkdir(parents=True, exist_ok=True)

    missing = []
    for skill_name in plugin["skills"]:
        src = skills_root / skill_name
        if not src.is_dir():
            missing.append(skill_name)
            continue
        if not (src / "SKILL.md").exists():
            print(f"WARN: {name}/{skill_name} has no SKILL.md", file=sys.stderr)
        shutil.copytree(src, skills_dir / skill_name)

    if missing:
        raise SystemExit(
            f"ERROR: plugin {name!r} references skills not present in "
            f"{upstream['submodule']} @ {upstream['pinned_tag']}: {missing}"
        )

    write_json(
        plugin_dir / ".claude-plugin" / "plugin.json",
        {
            "name": name,
            "version": "0.1.0",
            "description": plugin["description"],
            "author": {"name": "galeep"},
            "homepage": "https://github.com/galeep/plugin-place",
            "license": upstream["license"],
            "keywords": ["scientific-skills", upstream["upstream_repo"].split("/")[1]],
        },
    )

    readme = plugin_dir / "README.md"
    skill_list = "\n".join(f"- `{s}`" for s in plugin["skills"])
    readme.write_text(
        f"""# {name}

{plugin["description"]}

## Skills ({len(plugin["skills"])})

{skill_list}

## Provenance

Built from [{upstream['upstream_repo']}](https://github.com/{upstream['upstream_repo']}) @ `{upstream['pinned_tag']}`.
Skills are vendored copies under [MIT license]({upstream['license']}). All credit to K-Dense AI.

This plugin is generated by `scripts/build.sh` from `plugins.yaml`. Edits here will be overwritten on rebuild.
"""
    )


def build_vendored_plugin(plugin: dict, upstream: dict) -> None:
    """Copy a complete upstream plugin into plugins/<name>/, generate plugin.json."""
    name = plugin["name"]
    submodule_path = REPO_ROOT / upstream["submodule"]
    plugin_dir = PLUGINS_DIR / name
    plugin_dir.mkdir(parents=True, exist_ok=True)

    # Copy skills and commands wholesale if they exist upstream.
    for subdir in ("skills", "commands", "agents", "hooks"):
        src = submodule_path / subdir
        if src.is_dir():
            shutil.copytree(src, plugin_dir / subdir)

    # Drop container directories under skills/ that are not themselves skills
    # (no SKILL.md at their root). K-Dense's writer ships `document-skills/`
    # as a container with 4 sub-skills inside, but Claude Code expects skills
    # one level deep under skills/. Those skills are split into their own
    # `built` plugin (see kdense-document-skills); we drop the container here
    # to keep the writer plugin valid.
    skills_root_dir = plugin_dir / "skills"
    if skills_root_dir.is_dir():
        for container in list(skills_root_dir.iterdir()):
            if not container.is_dir() or (container / "SKILL.md").exists():
                continue
            print(f"  dropping container directory: {container.name}/", file=sys.stderr)
            shutil.rmtree(container)

    # If upstream has .mcp.json or .lsp.json at root, copy those too.
    for mcp_file in (".mcp.json", ".lsp.json"):
        src = submodule_path / mcp_file
        if src.is_file():
            shutil.copy2(src, plugin_dir / mcp_file)

    # Generate plugin.json — pull metadata from upstream marketplace.json if present.
    upstream_marketplace = submodule_path / ".claude-plugin" / "marketplace.json"
    description = plugin["description"]
    version = "0.1.0"
    if upstream_marketplace.exists():
        try:
            data = json.loads(upstream_marketplace.read_text())
            version = data.get("metadata", {}).get("version", version)
        except Exception:
            pass

    write_json(
        plugin_dir / ".claude-plugin" / "plugin.json",
        {
            "name": name,
            "version": version,
            "description": description,
            "author": {"name": "K-Dense Inc.", "email": "contact@k-dense.ai"},
            "homepage": f"https://github.com/{upstream['upstream_repo']}",
            "license": upstream["license"],
        },
    )

    plugin_dir.joinpath("README.md").write_text(
        f"""# {name}

{description}

## Provenance

Vendored from [{upstream['upstream_repo']}](https://github.com/{upstream['upstream_repo']}) @ `{upstream['pinned_tag']}`.
Licensed under {upstream['license']}. All credit to K-Dense AI.

This plugin is generated by `scripts/build.sh` from `plugins.yaml`. Edits here will be overwritten on rebuild.
"""
    )


def build_marketplace(config: dict) -> None:
    entries = []
    for plugin in config["plugins"]:
        entry = {
            "name": plugin["name"],
            "description": plugin["description"],
            "source": f"./plugins/{plugin['name']}",
        }
        if "category" in plugin:
            entry["category"] = plugin["category"]
        entries.append(entry)

    market = config["marketplace"]
    output = {
        "$schema": "https://json.schemastore.org/claude-code-marketplace.json",
        "name": market["name"],
        "version": market.get("version", "0.1.0"),
        "description": market["description"],
        "owner": market["owner"],
        "plugins": entries,
    }
    if "homepage" in market:
        output["metadata"] = {"homepage": market["homepage"]}
    write_json(MARKETPLACE_JSON, output)


def write_provenance_sidecar(config: dict) -> None:
    """Write a small JSON file recording exactly which upstream commits we built from.
    CI compares this to detect drift."""
    upstreams = {}
    for name, up in config["upstreams"].items():
        submodule_path = REPO_ROOT / up["submodule"]
        upstreams[name] = {
            "pinned_tag": up["pinned_tag"],
            "sha": submodule_sha(submodule_path),
            "describe": submodule_describe(submodule_path),
            "repo": up["upstream_repo"],
        }
    write_json(REPO_ROOT / ".claude-plugin" / "provenance.json", upstreams)


def main():
    config = yaml.safe_load(PLUGINS_YAML.read_text())

    clean_built_plugins()

    built = vendored = 0
    for plugin in config["plugins"]:
        kind = plugin["kind"]
        upstream_name = plugin.get("upstream")
        if kind in ("built", "vendored"):
            if upstream_name not in config["upstreams"]:
                raise SystemExit(
                    f"plugin {plugin['name']} references unknown upstream {upstream_name!r}"
                )
            upstream = config["upstreams"][upstream_name]

        if kind == "built":
            build_built_plugin(plugin, upstream)
            built += 1
        elif kind == "vendored":
            build_vendored_plugin(plugin, upstream)
            vendored += 1
        elif kind == "local":
            # local plugins live untouched in plugins/<name>/ already
            pass
        else:
            raise SystemExit(f"unknown plugin kind: {kind!r}")

    build_marketplace(config)
    write_provenance_sidecar(config)

    print(f"render.py: built={built} vendored={vendored} total={len(config['plugins'])}")


if __name__ == "__main__":
    main()
